version: "3.8"
services:
  web:
    image: nginx:latest
    restart: always
    volumes:
      - .:/var/www/html
      - .docker/nginx/conf.d:/etc/nginx/conf.d
      - .docker/nginx/certbot/conf:/etc/nginx/ssl
      - .docker/nginx/certbot/data:/var/www/certbot
    ports:
      - 80:80
      - 443:443

  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot --email inf@array42.com --agree-tos --no-eff-email -d array42.com -d www.array42.com
    volumes:
      - .docker/certbot/conf:/etc/letsencrypt
      - .docker/certbot/logs:/var/log/letsencrypt
      - .docker/certbot/data:/var/www/certbot